### ISSUE TITLE
Error when exiting a program

### ISSUE THREAD

**Issue by garncarz** [mitsuhiko/pluginbase#7]
```
Exception ignored in: <bound method PluginSource.__del__ of <pluginbase.PluginSource object at 0x7f1a4e229be0>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pluginbase.py", line 247, in __del__
  File "/usr/lib/python3.4/site-packages/pluginbase.py", line 303, in cleanup
  File "/usr/lib/python3.4/site-packages/pluginbase.py", line 318, in __cleanup
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by zeroSteiner** [comment]
I can't reproduce this error. Can you provide some more details regarding how pluginbase is being used? I see where the error is in the stack trace and code but not how the conditions can be set for it to be triggered.

**Comment by valgarf** [comment]
I had the same issue, appearing seemingly at random. Some very strange order during garbage collection I assume. Changing line 310 in `PluginSource.__cleanup` from
`if self.mod is None:`
to
`if self.mod is None or self.mod.__name__ is None:`
fixed it for me. (pluginbase version 0.4)

**Comment by Kamik423** [comment]
having the same error when exiting the program with
`sys.exit()`
is printed 1-4 times in a row. every single time. can this please be fixed in a future release?

**Comment by zeroSteiner** [comment]
@Kamik423 does the proposed work around fix the issue for you as well? I hesitate to patch a bug that I can't reproduce but would be more inclined to do so if multiple sources can confirm that it addresses it when the changes seem as reasonable as they do.

**Comment by Kamik423** [comment]
I did not try the workaround, because I want the software to be distributed, so I cannot expect everyone to fix this bug on their own

**Comment by zeroSteiner** [comment]
I'm still having a lot of trouble with reproducing this error. I've tried using `gc.collect` on demand, multiple threads, circular references, and explicitly deleting references. Each time I've tried a new test case I've run the script 500+ times due to the reports of this issue being intermittent.

Without being able to reproduce the error, I can't provide a reliable solution.

**Comment by Kamik423** [comment]
Well for me it was calling `sys.exit()` from an imported module

**Comment by GeorgeTG** [comment]
I have the same problem, and I can reproduce it 90% of the times. It happens when calling `sys.exit()` but I am not calling it from an imported module.

Even if you check that self.mod is not None, its ` __name__ ` attribute is None, which might mean that the module object is **partially** deleted. This happens because, for some reason, when Python is exiting, `ModuleType` objects are preferred in the cleanup order.

I think that this check is prone to gc related race conditions, and using an EAFP approach would be safer. 

The workaround proposed by @valgarf also works.

**Comment by zeroSteiner** [comment]
The proposed change is in version 0.5 which has just been uploaded to PyPi.
